spring.application.name=gameanalytics-backoffice

# Canlı ortam (Azure) ayarları
server.port=${http.port:8080}
spring.datasource.url=jdbc:postgresql://gameanalytics-db.postgres.database.azure.com:5432/gameanalytics?sslmode=require
spring.datasource.username=postgresadmin
spring.datasource.password=GameAnalytics2026!

# JPA Ayarlari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Vaadin üretim (production) modu
vaadin.productionMode=true